
package com.cd.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MerchantImplService", targetNamespace = "http://service.cd.com/", wsdlLocation = "http://localhost:8888/ws/merchantInfo?wsdl")
public class MerchantImplService
    extends Service
{

    private final static URL MERCHANTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MERCHANTIMPLSERVICE_EXCEPTION;
    private final static QName MERCHANTIMPLSERVICE_QNAME = new QName("http://service.cd.com/", "MerchantImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/ws/merchantInfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MERCHANTIMPLSERVICE_WSDL_LOCATION = url;
        MERCHANTIMPLSERVICE_EXCEPTION = e;
    }

    public MerchantImplService() {
        super(__getWsdlLocation(), MERCHANTIMPLSERVICE_QNAME);
    }

    public MerchantImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MERCHANTIMPLSERVICE_QNAME, features);
    }

    public MerchantImplService(URL wsdlLocation) {
        super(wsdlLocation, MERCHANTIMPLSERVICE_QNAME);
    }

    public MerchantImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MERCHANTIMPLSERVICE_QNAME, features);
    }

    public MerchantImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MerchantImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MerchantImpl
     */
    @WebEndpoint(name = "MerchantImplPort")
    public MerchantImpl getMerchantImplPort() {
        return super.getPort(new QName("http://service.cd.com/", "MerchantImplPort"), MerchantImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MerchantImpl
     */
    @WebEndpoint(name = "MerchantImplPort")
    public MerchantImpl getMerchantImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cd.com/", "MerchantImplPort"), MerchantImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MERCHANTIMPLSERVICE_EXCEPTION!= null) {
            throw MERCHANTIMPLSERVICE_EXCEPTION;
        }
        return MERCHANTIMPLSERVICE_WSDL_LOCATION;
    }

}
